
common_eval:
  path: ???

task:
  _name: ???
  bpe_dir: ../../utils/BPE

dataset:
  num_workers: 8
  batch_size: 16
  gen_subset: ???

common:
  bf16: true
  memory_efficient_bf16: true
  log_format: simple
  log_interval: 10
  seed: 3407
  user_dir: ../../user_module

model:
  _name: ???
